# Code generated by servicegen from dependencies.yaml. DO NOT EDIT.

VERSIONS = {
    "abseil": "20260526.0",
    "conan": "2.31.1",
    "grpc": "1.83.1",
    "libcron": "1.3.3",
    "librdkafka": "2.8.0",
    "liburing": "2.15",
    "openssl": "3.6.3",
    "protobuf": "6.33.5",
    "re2": "20251105",
    "userver": "3.2.0",
    "userver-boost": "1.87.0",
    "userver-googleapis": "2023.5.1",
    "userver-googletest": "1.15.0",
    "userver-opentelemetry-proto": "1.4.0",
    "yaml-cpp": "0.8.0",
}


if __name__ == "__main__":
    import sys

    if len(sys.argv) != 2 or sys.argv[1] not in VERSIONS:
        names = ", ".join(sorted(VERSIONS))
        raise SystemExit(f"usage: {sys.argv[0]} <version>; known: {names}")
    print(VERSIONS[sys.argv[1]])
