# Code generated by servicegen from dependencies.yaml. DO NOT EDIT.
[options]
boost/*:without_charconv=True
boost/*:without_cobalt=True
boost/*:without_contract=True
boost/*:without_fiber=True
boost/*:without_graph=True
boost/*:without_json=True
boost/*:without_log=True
boost/*:without_math=True
boost/*:without_nowide=True
boost/*:without_process=True
boost/*:without_serialization=True
boost/*:without_test=True
boost/*:without_timer=True
boost/*:without_type_erasure=True
boost/*:without_url=True
boost/*:without_wave=True
