#!/usr/bin/env python3
"""
Generates api/serviceapi.hpp and api/serviceapi_parse.hpp from
servicelib/api/serviceapi.yaml.
Usage: python3 generate.py  (run from any directory)
"""

import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("pip install pyyaml", file=sys.stderr)
    sys.exit(1)

SCRIPT_DIR = Path(__file__).parent
SCHEMA_FILE = SCRIPT_DIR.parent.parent.parent.parent / "servicelib/api/serviceapi.yaml"
OUT_FILE = SCRIPT_DIR / "serviceapi.hpp"
OUT_PARSE_FILE = SCRIPT_DIR / "serviceapi_parse.hpp"

SKIP_SCHEMAS = {"UndefinedEnum"}

HEADER = """\
/*
 * Copyright (c) 2024 Sergey Alexeev
 * Email: sergeyalexeev@yahoo.com
 *
 *  Licensed under the MIT License. See the [LICENSE](https://opensource.org/licenses/MIT) file for details.
 */

// Code generated by api/generate.py from servicelib/api/serviceapi.yaml. DO NOT EDIT.
#pragma once

namespace servicelib::api {
"""

FOOTER = """
}  // namespace servicelib::api
"""

PARSE_HEADER = """\
/*
 * Copyright (c) 2024 Sergey Alexeev
 * Email: sergeyalexeev@yahoo.com
 *
 *  Licensed under the MIT License. See the [LICENSE](https://opensource.org/licenses/MIT) file for details.
 */

// Code generated by api/generate.py from servicelib/api/serviceapi.yaml. DO NOT EDIT.
//
// YAML (de)serialization for the enums in serviceapi.hpp, via userver's
// utils::TrivialBiMap. Integer enums use x-enum-varnames because topology
// YAML writes symbolic names for them. String enums use their actual OpenAPI
// enum values, matching Go's generated wire representation.
#pragma once

#include <userver/formats/parse/to.hpp>
#include <userver/formats/yaml/value.hpp>
#include <userver/utils/trivial_map.hpp>

#include <servicelib/api/serviceapi.hpp>

namespace servicelib::api {
"""

PARSE_FOOTER = """
}  // namespace servicelib::api
"""


def to_cpp_name(raw: str) -> str:
    """Convert x-enum-varname to kCamelCase C++ enumerator name."""
    if "_" in raw or "-" in raw:
        parts = re.split(r"[_\-]", raw)
        camel = "".join(p.capitalize() for p in parts)
    else:
        camel = raw[0].upper() + raw[1:] if raw else raw
    return f"k{camel}"


def generate_enum(name: str, schema: dict) -> str | None:
    varnames = schema.get("x-enum-varnames", [])
    if not varnames:
        return None

    enum_values = schema["enum"]
    is_integer = schema.get("type") == "integer" and all(isinstance(v, int) for v in enum_values)

    lines = [f"enum class {name} {{"]
    for i, vn in enumerate(varnames):
        cpp_val = enum_values[i] if is_integer else i
        lines.append(f"  {to_cpp_name(vn)} = {cpp_val},  // {vn}")
    lines.append("};")
    return "\n".join(lines)


def generate_parse_block(name: str, schema: dict) -> str | None:
    varnames = schema.get("x-enum-varnames", [])
    if not varnames:
        return None

    enum_values = schema["enum"]
    is_integer = schema.get("type") == "integer" and all(isinstance(v, int) for v in enum_values)
    wire_values = varnames if is_integer else enum_values

    map_name = f"k{name}Map"
    lines = [f"constexpr userver::utils::TrivialBiMap {map_name} = [](auto selector) {{"]
    lines.append("  return selector()")
    for vn, wire_value in zip(varnames, wire_values, strict=True):
        escaped_wire_value = str(wire_value).replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'      .Case("{escaped_wire_value}", {name}::{to_cpp_name(vn)})')
    lines[-1] += ";"
    lines.append("};")
    lines.append("")
    lines.append(
        f"inline {name} Parse(const userver::formats::yaml::Value& value,\n"
        f"                    userver::formats::parse::To<{name}>) {{\n"
        f"  return userver::utils::ParseFromValueString(value, {map_name});\n"
        f"}}"
    )
    return "\n".join(lines)


def main() -> None:
    if not SCHEMA_FILE.exists():
        print(f"Schema file not found: {SCHEMA_FILE}", file=sys.stderr)
        sys.exit(1)

    data = yaml.safe_load(SCHEMA_FILE.read_text())
    schemas = data.get("components", {}).get("schemas", {})

    enum_blocks = []
    parse_blocks = []
    for name, schema in schemas.items():
        if name in SKIP_SCHEMAS:
            continue
        if "enum" in schema and "x-enum-varnames" in schema:
            block = generate_enum(name, schema)
            if block:
                enum_blocks.append(block)
            parse_block = generate_parse_block(name, schema)
            if parse_block:
                parse_blocks.append(parse_block)

    OUT_FILE.write_text(HEADER + "\n\n".join(enum_blocks) + FOOTER)
    print(f"Generated {OUT_FILE}")

    OUT_PARSE_FILE.write_text(PARSE_HEADER + "\n\n".join(parse_blocks) + PARSE_FOOTER)
    print(f"Generated {OUT_PARSE_FILE}")


if __name__ == "__main__":
    main()
