/*
 * Copyright (c) 2024 Sergey Alexeev
 * Email: sergeyalexeev@yahoo.com
 *
 *  Licensed under the MIT License. See the [LICENSE](https://opensource.org/licenses/MIT) file for details.
 */

// Code generated by api/generate.py from servicelib/api/serviceapi.yaml. DO NOT EDIT.
#pragma once

namespace servicelib::api {
enum class ProgrammingLanguage {
  kUndefined = 0,  // Undefined
  kGoLang = 1,  // GoLang
  kCppUserver = 2,  // CppUserver
  kPython = 3,  // Python
  kRust = 4,  // Rust
  kCppBoost = 5,  // CppBoost
  kTypeScript = 6,  // TypeScript
};

enum class JoinStorageType {
  kUndefined = 0,  // Undefined
  kHashMap = 1,  // HashMap
  kRocksDB = 2,  // RocksDB
  kAerospike = 3,  // Aerospike
};

enum class TransformationType {
  kUndefined = 0,  // Undefined
  kInput = 1,  // Input
  kMap = 2,  // Map
  kFilter = 3,  // Filter
  kJoin = 4,  // Join
  kMultiJoin = 5,  // MultiJoin
  kProcess = 6,  // Process
  kFlatMap = 7,  // FlatMap
  kFlatMapIterable = 8,  // FlatMapIterable
  kKeyBy = 9,  // KeyBy
  kMerge = 10,  // Merge
  kSplit = 11,  // Split
  kCase = 12,  // Case
  kSink = 13,  // Sink
  kCycleLink = 14,  // CycleLink
  kError = 15,  // Error
  kDelay = 16,  // Delay
  kWhen = 17,  // When
};

enum class JoinType {
  kUndefined = 0,  // Undefined
  kInner = 1,  // Inner
  kLeft = 2,  // Left
  kRight = 3,  // Right
  kOuter = 4,  // Outer
};

enum class HTTPMethodType {
  kUndefined = 0,  // Undefined
  kGET = 1,  // GET
  kPOST = 2,  // POST
};

enum class GrpcMethodType {
  kUndefined = 0,  // Undefined
  kNoStreaming = 1,  // NoStreaming
  kClientStreaming = 2,  // ClientStreaming
  kServerStreaming = 4,  // ServerStreaming
  kBidirectionalStreaming = 5,  // BidirectionalStreaming
};

enum class CallSemantics {
  kUndefined = 0,  // Undefined
  kInherited = 1,  // Inherited
  kFunctionCall = 2,  // FunctionCall
  kTaskPool = 3,  // TaskPool
  kPriorityTaskPool = 4,  // PriorityTaskPool
  kParallelCall = 5,  // ParallelCall
};

enum class DataConnectorType {
  kUndefined = 0,  // Undefined
  kHTTP = 1,  // HTTP
  kGRPC = 2,  // gRPC
  kKafka = 3,  // Kafka
  kCustom = 4,  // Custom
  kCron = 5,  // Cron
  kTemporal = 6,  // Temporal
};

enum class ProcessPattern {
  kUndefined = 0,  // Undefined
  kExecute = 1,  // Execute
  kCollect = 2,  // Collect
};

enum class LogLevel {
  kUndefined = 0,  // Undefined
  kCRITICAL = 1,  // CRITICAL
  kFATAL = 2,  // FATAL
  kERROR = 3,  // ERROR
  kWARNING = 4,  // WARNING
  kINFO = 5,  // INFO
  kDEBUG = 6,  // DEBUG
};

enum class Environment {
  kUndefined = 0,  // Undefined
  kLocal = 1,  // Local
  kDebug = 2,  // Debug
  kStaging = 3,  // Staging
  kProduction = 4,  // Production
};

enum class KubernetesWorkloadType {
  kDeployment = 0,  // Deployment
  kStatefulSet = 1,  // StatefulSet
};

enum class DataConnectorImplementation {
  kUndefined = 0,  // Undefined
  kNetHTTP = 1,  // NetHTTP
  kFunction = 2,  // Function
  kIBMsarama = 3,  // IBMsarama
  kGoogleGRPC = 4,  // GoogleGRPC
  kUserverHTTP = 5,  // UserverHTTP
  kUserverGRPC = 6,  // UserverGRPC
  kUserverKafka = 7,  // UserverKafka
  kBoostBeastHTTP = 8,  // BoostBeastHTTP
  kAsioGRPC = 9,  // AsioGRPC
  kLibrdkafka = 10,  // Librdkafka
  kAioHTTP = 11,  // AioHTTP
  kAioKafka = 12,  // AioKafka
  kRustAxum = 13,  // RustAxum
  kRustTonic = 14,  // RustTonic
  kRustRdkafka = 15,  // RustRdkafka
  kNodeHTTP = 16,  // NodeHTTP
  kGrpcJS = 17,  // GrpcJS
  kConfluentKafkaJavaScript = 18,  // ConfluentKafkaJavaScript
  kGoGocron = 19,  // GoGocron
  kPythonAPScheduler = 20,  // PythonAPScheduler
  kRustCroner = 21,  // RustCroner
  kNodeCroner = 22,  // NodeCroner
  kCppLibcron = 23,  // CppLibcron
  kTemporalGo = 24,  // TemporalGo
  kTemporalPython = 25,  // TemporalPython
  kTemporalTypeScript = 26,  // TemporalTypeScript
};

enum class KafkaSecurityProtocol {
  kPLAINTEXT = 0,  // PLAINTEXT
  kSASLPLAINTEXT = 1,  // SASLPLAINTEXT
  kSASLSSL = 2,  // SASLSSL
};

enum class KafkaSaslMechanism {
  kPLAIN = 0,  // PLAIN
  kSCRAMSHA256 = 1,  // SCRAMSHA256
  kSCRAMSHA512 = 2,  // SCRAMSHA512
};

enum class ScheduleOverlapPolicy {
  kAllow = 0,  // Allow
  kSkip = 1,  // Skip
};

enum class ScheduleMissedRunPolicy {
  kSkip = 0,  // Skip
  kFireOnce = 1,  // FireOnce
};

enum class TypeDefinitionFormat {
  kUndefined = 0,  // Undefined
  kNative = 1,  // Native
  kProtobuf = 2,  // Protobuf
  kFlatBuffers = 3,  // FlatBuffers
  kCapNProto = 4,  // CapNProto
  kOpenAPI = 5,  // OpenAPI
};

enum class DataType {
  kUndefined = 0,  // Undefined
  kInt = 1,  // int
  kUint = 2,  // uint
  kByte = 3,  // byte
  kChar = 4,  // char
  kBoolean = 5,  // boolean
  kUnicodeChar = 6,  // unicodeChar
  kString = 7,  // string
  kUnicodeString = 8,  // unicodeString
  kFloat = 9,  // float
  kDouble = 10,  // double
  kInt8 = 11,  // int8
  kInt16 = 12,  // int16
  kInt32 = 13,  // int32
  kInt64 = 14,  // int64
  kUint8 = 15,  // uint8
  kUint16 = 16,  // uint16
  kUint32 = 17,  // uint32
  kUint64 = 18,  // uint64
  kAny = 19,  // any
  kError = 20,  // error
  kScheduleTrigger = 21,  // scheduleTrigger
  kArray = 22,  // array
  kMap = 23,  // map
  kStruct = 24,  // struct
  kCustom = 25,  // custom
};
}  // namespace servicelib::api
