/*
 * Copyright (c) 2024 Sergey Alexeev
 * Email: sergeyalexeev@yahoo.com
 *
 *  Licensed under the MIT License. See the [LICENSE](https://opensource.org/licenses/MIT) file for details.
 */

// Code generated by api/generate.py from servicelib/api/serviceapi.yaml. DO NOT EDIT.
//
// YAML (de)serialization for the enums in serviceapi.hpp, via userver's
// utils::TrivialBiMap. Integer enums use x-enum-varnames because topology
// YAML writes symbolic names for them. String enums use their actual OpenAPI
// enum values, matching Go's generated wire representation.
#pragma once

#include <userver/formats/parse/to.hpp>
#include <userver/formats/yaml/value.hpp>
#include <userver/utils/trivial_map.hpp>

#include <servicelib/api/serviceapi.hpp>

namespace servicelib::api {
constexpr userver::utils::TrivialBiMap kProgrammingLanguageMap = [](auto selector) {
  return selector()
      .Case("Undefined", ProgrammingLanguage::kUndefined)
      .Case("GoLang", ProgrammingLanguage::kGoLang)
      .Case("CppUserver", ProgrammingLanguage::kCppUserver)
      .Case("Python", ProgrammingLanguage::kPython)
      .Case("Rust", ProgrammingLanguage::kRust)
      .Case("CppBoost", ProgrammingLanguage::kCppBoost)
      .Case("TypeScript", ProgrammingLanguage::kTypeScript);
};

inline ProgrammingLanguage Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<ProgrammingLanguage>) {
  return userver::utils::ParseFromValueString(value, kProgrammingLanguageMap);
}

constexpr userver::utils::TrivialBiMap kJoinStorageTypeMap = [](auto selector) {
  return selector()
      .Case("Undefined", JoinStorageType::kUndefined)
      .Case("HashMap", JoinStorageType::kHashMap)
      .Case("RocksDB", JoinStorageType::kRocksDB)
      .Case("Aerospike", JoinStorageType::kAerospike);
};

inline JoinStorageType Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<JoinStorageType>) {
  return userver::utils::ParseFromValueString(value, kJoinStorageTypeMap);
}

constexpr userver::utils::TrivialBiMap kTransformationTypeMap = [](auto selector) {
  return selector()
      .Case("Undefined", TransformationType::kUndefined)
      .Case("Input", TransformationType::kInput)
      .Case("Map", TransformationType::kMap)
      .Case("Filter", TransformationType::kFilter)
      .Case("Join", TransformationType::kJoin)
      .Case("MultiJoin", TransformationType::kMultiJoin)
      .Case("Process", TransformationType::kProcess)
      .Case("FlatMap", TransformationType::kFlatMap)
      .Case("FlatMapIterable", TransformationType::kFlatMapIterable)
      .Case("KeyBy", TransformationType::kKeyBy)
      .Case("Merge", TransformationType::kMerge)
      .Case("Split", TransformationType::kSplit)
      .Case("Case", TransformationType::kCase)
      .Case("Sink", TransformationType::kSink)
      .Case("CycleLink", TransformationType::kCycleLink)
      .Case("Error", TransformationType::kError)
      .Case("Delay", TransformationType::kDelay)
      .Case("When", TransformationType::kWhen);
};

inline TransformationType Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<TransformationType>) {
  return userver::utils::ParseFromValueString(value, kTransformationTypeMap);
}

constexpr userver::utils::TrivialBiMap kJoinTypeMap = [](auto selector) {
  return selector()
      .Case("Undefined", JoinType::kUndefined)
      .Case("Inner", JoinType::kInner)
      .Case("Left", JoinType::kLeft)
      .Case("Right", JoinType::kRight)
      .Case("Outer", JoinType::kOuter);
};

inline JoinType Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<JoinType>) {
  return userver::utils::ParseFromValueString(value, kJoinTypeMap);
}

constexpr userver::utils::TrivialBiMap kHTTPMethodTypeMap = [](auto selector) {
  return selector()
      .Case("", HTTPMethodType::kUndefined)
      .Case("GET", HTTPMethodType::kGET)
      .Case("POST", HTTPMethodType::kPOST);
};

inline HTTPMethodType Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<HTTPMethodType>) {
  return userver::utils::ParseFromValueString(value, kHTTPMethodTypeMap);
}

constexpr userver::utils::TrivialBiMap kGrpcMethodTypeMap = [](auto selector) {
  return selector()
      .Case("Undefined", GrpcMethodType::kUndefined)
      .Case("NoStreaming", GrpcMethodType::kNoStreaming)
      .Case("ClientStreaming", GrpcMethodType::kClientStreaming)
      .Case("ServerStreaming", GrpcMethodType::kServerStreaming)
      .Case("BidirectionalStreaming", GrpcMethodType::kBidirectionalStreaming);
};

inline GrpcMethodType Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<GrpcMethodType>) {
  return userver::utils::ParseFromValueString(value, kGrpcMethodTypeMap);
}

constexpr userver::utils::TrivialBiMap kCallSemanticsMap = [](auto selector) {
  return selector()
      .Case("Undefined", CallSemantics::kUndefined)
      .Case("Inherited", CallSemantics::kInherited)
      .Case("FunctionCall", CallSemantics::kFunctionCall)
      .Case("TaskPool", CallSemantics::kTaskPool)
      .Case("PriorityTaskPool", CallSemantics::kPriorityTaskPool)
      .Case("ParallelCall", CallSemantics::kParallelCall);
};

inline CallSemantics Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<CallSemantics>) {
  return userver::utils::ParseFromValueString(value, kCallSemanticsMap);
}

constexpr userver::utils::TrivialBiMap kDataConnectorTypeMap = [](auto selector) {
  return selector()
      .Case("Undefined", DataConnectorType::kUndefined)
      .Case("HTTP", DataConnectorType::kHTTP)
      .Case("gRPC", DataConnectorType::kGRPC)
      .Case("Kafka", DataConnectorType::kKafka)
      .Case("Custom", DataConnectorType::kCustom)
      .Case("Cron", DataConnectorType::kCron)
      .Case("Temporal", DataConnectorType::kTemporal);
};

inline DataConnectorType Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<DataConnectorType>) {
  return userver::utils::ParseFromValueString(value, kDataConnectorTypeMap);
}

constexpr userver::utils::TrivialBiMap kProcessPatternMap = [](auto selector) {
  return selector()
      .Case("Undefined", ProcessPattern::kUndefined)
      .Case("Execute", ProcessPattern::kExecute)
      .Case("Collect", ProcessPattern::kCollect);
};

inline ProcessPattern Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<ProcessPattern>) {
  return userver::utils::ParseFromValueString(value, kProcessPatternMap);
}

constexpr userver::utils::TrivialBiMap kLogLevelMap = [](auto selector) {
  return selector()
      .Case("", LogLevel::kUndefined)
      .Case("CRITICAL", LogLevel::kCRITICAL)
      .Case("FATAL", LogLevel::kFATAL)
      .Case("ERROR", LogLevel::kERROR)
      .Case("WARNING", LogLevel::kWARNING)
      .Case("INFO", LogLevel::kINFO)
      .Case("DEBUG", LogLevel::kDEBUG);
};

inline LogLevel Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<LogLevel>) {
  return userver::utils::ParseFromValueString(value, kLogLevelMap);
}

constexpr userver::utils::TrivialBiMap kEnvironmentMap = [](auto selector) {
  return selector()
      .Case("", Environment::kUndefined)
      .Case("local", Environment::kLocal)
      .Case("debug", Environment::kDebug)
      .Case("staging", Environment::kStaging)
      .Case("production", Environment::kProduction);
};

inline Environment Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<Environment>) {
  return userver::utils::ParseFromValueString(value, kEnvironmentMap);
}

constexpr userver::utils::TrivialBiMap kKubernetesWorkloadTypeMap = [](auto selector) {
  return selector()
      .Case("Deployment", KubernetesWorkloadType::kDeployment)
      .Case("StatefulSet", KubernetesWorkloadType::kStatefulSet);
};

inline KubernetesWorkloadType Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<KubernetesWorkloadType>) {
  return userver::utils::ParseFromValueString(value, kKubernetesWorkloadTypeMap);
}

constexpr userver::utils::TrivialBiMap kDataConnectorImplementationMap = [](auto selector) {
  return selector()
      .Case("", DataConnectorImplementation::kUndefined)
      .Case("net/http", DataConnectorImplementation::kNetHTTP)
      .Case("function", DataConnectorImplementation::kFunction)
      .Case("IBM/Sarama", DataConnectorImplementation::kIBMsarama)
      .Case("google/grpc", DataConnectorImplementation::kGoogleGRPC)
      .Case("userver/http", DataConnectorImplementation::kUserverHTTP)
      .Case("userver/grpc", DataConnectorImplementation::kUserverGRPC)
      .Case("userver/kafka", DataConnectorImplementation::kUserverKafka)
      .Case("boost/beast-http", DataConnectorImplementation::kBoostBeastHTTP)
      .Case("asio/grpc", DataConnectorImplementation::kAsioGRPC)
      .Case("librdkafka", DataConnectorImplementation::kLibrdkafka)
      .Case("aiohttp", DataConnectorImplementation::kAioHTTP)
      .Case("aiokafka", DataConnectorImplementation::kAioKafka)
      .Case("rust/axum", DataConnectorImplementation::kRustAxum)
      .Case("rust/tonic", DataConnectorImplementation::kRustTonic)
      .Case("rust/rdkafka", DataConnectorImplementation::kRustRdkafka)
      .Case("node/http", DataConnectorImplementation::kNodeHTTP)
      .Case("grpc/grpc-js", DataConnectorImplementation::kGrpcJS)
      .Case("confluent/kafka-javascript", DataConnectorImplementation::kConfluentKafkaJavaScript)
      .Case("go/gocron", DataConnectorImplementation::kGoGocron)
      .Case("python/apscheduler", DataConnectorImplementation::kPythonAPScheduler)
      .Case("rust/croner", DataConnectorImplementation::kRustCroner)
      .Case("node/croner", DataConnectorImplementation::kNodeCroner)
      .Case("cpp/libcron", DataConnectorImplementation::kCppLibcron)
      .Case("temporal/go", DataConnectorImplementation::kTemporalGo)
      .Case("temporal/python", DataConnectorImplementation::kTemporalPython)
      .Case("temporal/typescript", DataConnectorImplementation::kTemporalTypeScript);
};

inline DataConnectorImplementation Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<DataConnectorImplementation>) {
  return userver::utils::ParseFromValueString(value, kDataConnectorImplementationMap);
}

constexpr userver::utils::TrivialBiMap kKafkaSecurityProtocolMap = [](auto selector) {
  return selector()
      .Case("PLAINTEXT", KafkaSecurityProtocol::kPLAINTEXT)
      .Case("SASL_PLAINTEXT", KafkaSecurityProtocol::kSASLPLAINTEXT)
      .Case("SASL_SSL", KafkaSecurityProtocol::kSASLSSL);
};

inline KafkaSecurityProtocol Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<KafkaSecurityProtocol>) {
  return userver::utils::ParseFromValueString(value, kKafkaSecurityProtocolMap);
}

constexpr userver::utils::TrivialBiMap kKafkaSaslMechanismMap = [](auto selector) {
  return selector()
      .Case("PLAIN", KafkaSaslMechanism::kPLAIN)
      .Case("SCRAM-SHA-256", KafkaSaslMechanism::kSCRAMSHA256)
      .Case("SCRAM-SHA-512", KafkaSaslMechanism::kSCRAMSHA512);
};

inline KafkaSaslMechanism Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<KafkaSaslMechanism>) {
  return userver::utils::ParseFromValueString(value, kKafkaSaslMechanismMap);
}

constexpr userver::utils::TrivialBiMap kScheduleOverlapPolicyMap = [](auto selector) {
  return selector()
      .Case("Allow", ScheduleOverlapPolicy::kAllow)
      .Case("Skip", ScheduleOverlapPolicy::kSkip);
};

inline ScheduleOverlapPolicy Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<ScheduleOverlapPolicy>) {
  return userver::utils::ParseFromValueString(value, kScheduleOverlapPolicyMap);
}

constexpr userver::utils::TrivialBiMap kScheduleMissedRunPolicyMap = [](auto selector) {
  return selector()
      .Case("Skip", ScheduleMissedRunPolicy::kSkip)
      .Case("FireOnce", ScheduleMissedRunPolicy::kFireOnce);
};

inline ScheduleMissedRunPolicy Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<ScheduleMissedRunPolicy>) {
  return userver::utils::ParseFromValueString(value, kScheduleMissedRunPolicyMap);
}

constexpr userver::utils::TrivialBiMap kTemporalExecutionTypeMap = [](auto selector) {
  return selector()
      .Case("Activity", TemporalExecutionType::kActivity)
      .Case("Workflow", TemporalExecutionType::kWorkflow);
};

inline TemporalExecutionType Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<TemporalExecutionType>) {
  return userver::utils::ParseFromValueString(value, kTemporalExecutionTypeMap);
}

constexpr userver::utils::TrivialBiMap kTypeDefinitionFormatMap = [](auto selector) {
  return selector()
      .Case("Undefined", TypeDefinitionFormat::kUndefined)
      .Case("Native", TypeDefinitionFormat::kNative)
      .Case("Protobuf", TypeDefinitionFormat::kProtobuf)
      .Case("FlatBuffers", TypeDefinitionFormat::kFlatBuffers)
      .Case("CapNProto", TypeDefinitionFormat::kCapNProto)
      .Case("OpenAPI", TypeDefinitionFormat::kOpenAPI);
};

inline TypeDefinitionFormat Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<TypeDefinitionFormat>) {
  return userver::utils::ParseFromValueString(value, kTypeDefinitionFormatMap);
}

constexpr userver::utils::TrivialBiMap kDataTypeMap = [](auto selector) {
  return selector()
      .Case("", DataType::kUndefined)
      .Case("int", DataType::kInt)
      .Case("uint", DataType::kUint)
      .Case("byte", DataType::kByte)
      .Case("char", DataType::kChar)
      .Case("boolean", DataType::kBoolean)
      .Case("unicode char", DataType::kUnicodeChar)
      .Case("string", DataType::kString)
      .Case("unicode string", DataType::kUnicodeString)
      .Case("float", DataType::kFloat)
      .Case("double", DataType::kDouble)
      .Case("int8", DataType::kInt8)
      .Case("int16", DataType::kInt16)
      .Case("int32", DataType::kInt32)
      .Case("int64", DataType::kInt64)
      .Case("uint8", DataType::kUint8)
      .Case("uint16", DataType::kUint16)
      .Case("uint32", DataType::kUint32)
      .Case("uint64", DataType::kUint64)
      .Case("any", DataType::kAny)
      .Case("error", DataType::kError)
      .Case("schedule trigger", DataType::kScheduleTrigger)
      .Case("array", DataType::kArray)
      .Case("map", DataType::kMap)
      .Case("struct", DataType::kStruct)
      .Case("custom", DataType::kCustom);
};

inline DataType Parse(const userver::formats::yaml::Value& value,
                    userver::formats::parse::To<DataType>) {
  return userver::utils::ParseFromValueString(value, kDataTypeMap);
}
}  // namespace servicelib::api
