#!/usr/bin/env python3
"""Embed the status UI assets into the header-only C++ runtime."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "resources" / "status"
OUTPUT = (
    ROOT
    / "include"
    / "servicelib"
    / "runtime"
    / "status"
    / "web.generated.hpp"
)

ASSETS = {
    "kStatusHtml": "status.html",
    "kVisJavaScript": "vis.min.js",
    "kVisCss": "vis.min.css",
}


def raw_literal(name: str, value: str) -> str:
    delimiter = f"sl_{name.removeprefix('k')[:10]}"
    if f"){delimiter}\"" in value:
        raise ValueError(f"raw-string delimiter collision in {name}")
    return f'R"{delimiter}({value}){delimiter}"'


def main() -> None:
    lines = [
        "// Code generated by tools/generate-status-assets.py. DO NOT EDIT.",
        "#pragma once",
        "",
        "#include <string_view>",
        "",
        "namespace servicelib::status::web {",
        "",
    ]
    for variable, filename in ASSETS.items():
        contents = (ASSET_DIR / filename).read_text(encoding="utf-8")
        lines.extend(
            [
                f"inline constexpr std::string_view {variable} =",
                "    std::string_view{"
                f"{raw_literal(variable, contents)}, "
                f"{len(contents.encode('utf-8'))}"
                "};",
                "",
            ]
        )
    lines.append("}  // namespace servicelib::status::web")
    lines.append("")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
